### ISSUE TITLE
Don't works with aws-sdk-php

### ISSUE THREAD

**Issue by noerosell** [WyriHaximus/react-guzzle-psr7#26]
The `sign` step Middleware that Aws (version 3) adds in every request concludes with a non fulfilled promise, short-cutting the middleware chain, so when an aws async method is requested, the invoke method of your HttpClientAdapter is not reached and the react loop queue remains empty.

This promise makes an http request (to validate credentials ?), and is added to guzzle internal queue. This promise will never resolve until run method queue's is executed.

You can see Aws\Middleware file `signer` method, where the promise is created, returned to Aws\CredentialProvider `fromCredentials` method.

In my point of view this is not a bug of react-guzzle-psr7, may be can be avoided adding another middleware step which runs the guzzle queue ?

**Comment by WyriHaximus** [comment]
Hey, I've just filed #27 that does this for when after the `__invoke` has been called. For before `__invoke` is called. You could do this, that will keep ticking off items from the queue ensuring everything is handled:

```php
$timer = $this->loop->addPeriodicTimer(0.1, function () {
    \GuzzleHttp\Promise\queue()->run();
});
```

Be sure to cancel `$timer` when you don't have any left to do, or otherwise the loop keeps running.

**Comment by noerosell** [comment]
Ok. Thanks.
